In [6]:
print("The zero occurs at")
print(2*pi)
print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [7]:
cat("The zero occurs at", 2*pi, "radians.",
"\n")

The zero occurs at 6.283185 radians.

In [8]:
d = date()

In [9]:
cat("Today’s date is:", d, "\n" )

Today’s date is: Wed Sep 23 06:07:11 2026

In [10]:
x=1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [11]:
cat(x,sep=" ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [12]:
cat("\n")

In [13]:
cat(x,sep=" / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [18]:
x=7
cat("The square of", x, "is", x^2, "\n")

The square of 7 is 49

In [20]:
cat("The square root of",x,"is
approximately", format(sqrt(x),digits=3),"\n")

The square root of 7 is
approximately 2.65

In [21]:
evenno = c(2,4,6,8,10)
evenno

[1]  2  4  6  8 10

In [22]:
cat("the first few numbers are:", evenno, "...\n")

the first few numbers are: 2 4 6 8 10 ...

In [24]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [25]:
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [26]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [27]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [28]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

In [29]:
paste("Everybody", "loves", "R Programming.",
sep="*")

[1] "Everybody*loves*R Programming."

In [30]:
paste("Everybody", "loves", "R Programming.",
sep="===")

[1] "Everybody===loves===R Programming."

In [31]:
names = c("Prof. Singh", "Mr. Jha")

In [32]:
names

[1] "Prof. Singh" "Mr. Jha"

In [33]:
paste(names, "is", "a good", "person.")

[1] "Prof. Singh is a good person." "Mr. Jha is a good person."

In [35]:
paste(names, "is", "a good", "person.", collapse=", and ")

[1] "Prof. Singh is a good person., and Mr. Jha is a good person."

In [36]:
paste(1, " is first", 2, " is second", 3, " is third",
sep = "#")

[1] "1# is first#2# is second#3# is third"

In [37]:
paste(1, " is first   ", 2, " is second   ", 3, " is third    ",
sep = "#")

[1] "1# is first   #2# is second   #3# is third    "

In [38]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [39]:
x[1]

[1] "Ex_1"

In [40]:
x = paste("Ex", 1:5, sep="_", collapse="")

In [41]:
x = paste("Ex", 1:5, sep="_")

In [42]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [43]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [44]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [45]:
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [46]:
x = "The&!syntax&!of&!paste&!is!&available!
&inthe online-help"

In [47]:
x

[1] "The&!syntax&!of&!paste&!is!&available!\n&inthe online-help"

In [48]:
strsplit(x, split="!")

[[1]]
[1] "The&"                 "syntax&"              "of&"
[4] "paste&"               "is"                   "&available"
[7] "\n&inthe online-help"

In [49]:
strsplit(x, split = "&!")

[[1]]
[1] "The"                                "syntax"
[3] "of"                                 "paste"
[5] "is!&available!\n&inthe online-help"

In [50]:
y = strsplit(x, split = "!&")

In [51]:
y

[[1]]
[1] "The&!syntax&!of&!paste&!is"     "available!\n&inthe online-help"

In [52]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [53]:
y[[1]][2]

[1] "available!\n&inthe online-help"

In [54]:
y[[1]][3]

[1] NA

In [55]:
dates = c("2020-07-24", "2021-08-25", "2022-
09-26", "2023-10-27")

In [56]:
datesplt=strsplit(dates, "-")

In [57]:
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "\n09" "26"

[[4]]
[1] "2023" "10"   "27"

In [58]:
datemat=matrix(unlist(datesplt),nrow=4,ncol=3,byrow=TRUE)

In [59]:
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 \n09 26
[4,] 2023 10   27

In [60]:
datematrix =
matrix(as.numeric(unlist(datesplt)), nrow = 4,
ncol=3, byrow=TRUE)

In [61]:
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [63]:
strsplit("vidyalankar",split="")

[[1]]
 [1] "v" "i" "d" "y" "a" "l" "a" "n" "k" "a" "r"

In [64]:
x = "R course 24.07.2022"

In [65]:
y = "Number of participants: 25"

In [66]:
nchar(x)

[1] 19

In [67]:
nchar(y)

[1] 26

In [68]:
nzchar(x)

[1] TRUE

In [69]:
nzchar(y)

[1] TRUE

In [70]:
x = c("Apple", "Banana", "Cake")

In [71]:
x

[1] "Apple"  "Banana" "Cake"

In [72]:
nzchar(x)

[1] TRUE TRUE TRUE

In [73]:
nzchar(y)

[1] TRUE

In [74]:
tolower(x)

[1] "apple"  "banana" "cake"

In [75]:
toupper(x)

[1] "APPLE"  "BANANA" "CAKE"

In [76]:
x = "R course will start from 24.07.2022"

In [77]:
toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [78]:
z = "VIDYALANKAR INSTITUTE OF TECHNOLOGY"

In [80]:
tolower(z)

[1] "vidyalankar institute of technology"