In [1]:
x=NA
is.na(x)

[1] TRUE

In [3]:
x=c(11,NA,13,NA)
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

In [4]:
x=c(11,NA,13,NA)
mean(x)
mean(x,na.rm=TRUE)

[1] NA

[1] 12

In [5]:
x=c(11,NA,13,NA)
x

[1] 11 NA 13 NA

In [6]:
which(is.na(x))

[1] 2 4

In [8]:
x=c(11,NA,13,NA)
x

[1] 11 NA 13 NA

In [9]:
sum(is.na(x))

[1] 2

In [10]:
complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

In [11]:
y=na.omit(x)

In [12]:
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [13]:
x=c(11,NA,13,NA)
x
y=na.omit(x)
y

[1] 11 NA 13 NA

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [14]:
mean(x)

[1] NA

In [15]:
mean(y)

[1] 12

In [16]:
x=5
if(x>4)x*3
x=3
if(x>4)x*3

[1] 15

In [17]:
x=3
if(x>4) {x*3}

In [18]:
x=6
if(x>3){
  print("the value is more than 3")
}

[1] "the value is more than 3"

In [19]:
x=2
if(x>3){
  print("the value is more than 3")
}

In [20]:
x=5
if(x==3) {x=x-1} else {x=2*x}
x

[1] 10

In [21]:
x=3
if(x==3) {x=x-1} else {x=2*x}
x

[1] 2

In [23]:
x=6
if(x>3){
  print("the vale is more than 3")
}else{
  print("the value is less than 3")
}

[1] "the vale is more than 3"

In [24]:
x=2
if(x>3){
  print("the vale is more than 3")
}else{
  print("the value is less than 3")
}

[1] "the value is less than 3"

In [25]:
x=5
if(x==3){
  x=x-1
}else if (x<3){
  x=x+5
}else{x=2*x}
x

[1] 10

In [26]:
x=2
if(x==3){
  x=x-1
}else if (x<3){
  x=x+5
}else{x=2*x}
x

[1] 7

In [27]:
x=3
if(x==3){
  x=x-1
}else if (x<3){
  x=x+5
}else{x=2*x}
x

[1] 2

In [28]:
x=1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [29]:
ifelse(x<6,x^2,x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [31]:
x=c(7,9,8,4)
ifelse(x %% 2==0,"even number","odd number")

[1] "odd number"  "odd number"  "even number" "even number"

In [32]:
switch(2,"apple","banana","orange")

[1] "banana"

In [33]:
switch(1,"apple","banana","orange")

[1] "apple"

In [34]:
switch("colour","colour"="blue","gender"="male","volume"="50")

[1] "blue"

In [35]:
switch("volume","colour"="blue","gender"="male","volume"="50")

[1] "50"

In [36]:
switch(4,"apple", "banana", "orange")

In [38]:
switch("size", "colour" = "blue", "gender" =
"male", "volume" = 50)

In [39]:
x=c(10,15,8,14,6,12)
x

[1] 10 15  8 14  6 12

In [40]:
which(x==14)

[1] 4

In [41]:
which(x!=12)

[1] 1 2 3 4 5

In [42]:
which(x>10)

[1] 2 4 6

In [43]:
x=matrix(nrow=3,ncol=3,data=1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [44]:
x=matrix(nrow=3,ncol=3,data=1:9)

In [45]:
which(x%%2==1)

[1] 1 3 5 7 9

In [46]:
which(x%%2==1,arr.ind=TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3