In [1]:
 x = matrix( nrow=4, ncol=3, data=c(1:12) )

In [2]:
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [3]:
rownames(x)=c("r1","r2","r3","r4")

In [4]:
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [5]:
colnames(x)=c("c1","c2","c3")

In [6]:
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [7]:
x = matrix( nrow=4, ncol=2, data=2 )

In [8]:
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [9]:
d = diag(1, nrow=3, ncol=3)

In [10]:
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [11]:
d = diag(5, nrow=3, ncol=3)

In [12]:
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [13]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)

In [14]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [15]:
xt=t(x)

In [16]:
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [17]:
x=matrix(nrow=4,ncol=2,data=c(1,2,3,4,5,6,7,8))

In [18]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [19]:
x=matrix(nrow=4,ncol=2,data=c(1,2,3,4,5,6,7,8))

In [20]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [21]:
rowMeans(x)

[1] 3 4 5 6

In [22]:
colMeans(x)

[1] 2.5 6.5

In [23]:
x=matrix(nrow=5,ncol=3,byrow=T,data=1:15)

In [24]:
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [25]:
x[3,]

[1] 7 8 9

In [26]:
x[,2]

[1]  2  5  8 11 14

In [27]:
x[4:5,2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [28]:
x[c(1,4),c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [29]:
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [30]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)

In [31]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [32]:
x-5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

In [33]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [34]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

In [39]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)

In [40]:
y=matrix(nrow=4,ncol=2,data=11:18,byrow=T)

In [41]:
x+y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

In [42]:
x-y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [43]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)

In [44]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [45]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [46]:
x+4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [47]:
4*x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [48]:
x=matrix(nrow=4,ncol=2,data=1:8,byrow=T)

In [49]:
y=matrix(nrow=4,ncol=2,data=11:18,byrow=T)

In [54]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [55]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [57]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)

x %*% y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [58]:
y %*% x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [59]:
t(x) %*% t(y)

     [,1] [,2]
[1,] 210  274
[2,] 260  340

In [60]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [61]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [62]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [63]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [64]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [66]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [67]:
x = matrix(nrow=4, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:16, byrow=T)

Warning message in matrix(nrow = 4, ncol = 2, data = 1:6, byrow = T):
“data length [6] is not a sub-multiple or multiple of the number of rows [4]”
Warning message in matrix(nrow = 4, ncol = 2, data = 11:16, byrow = T):
“data length [6] is not a sub-multiple or multiple of the number of rows [4]”

In [68]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 1    2

In [69]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 11   12

In [70]:
rbind(x,y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,]  1    2
[5,] 11   12
[6,] 13   14
[7,] 15   16
[8,] 11   12

In [71]:
cbind(x,y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16
[4,] 1    2    11   12

In [72]:
y = matrix( nrow = 2, ncol = 2, byrow = T,
data = c(84,100,100,120))

In [73]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [74]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [75]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data
= c(84,100,100,120))

In [76]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [78]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [79]:
x=8

In [80]:
(x<10)||(x<2)

[1] TRUE

In [81]:
x=18
(x<10)||(x<2)

[1] FALSE

In [83]:
x = c(8,18)

In [86]:
(x < 10)|(x < 2)

[1]  TRUE FALSE

In [88]:
x=5
(x<10)&&(x>2)

[1] TRUE

In [89]:
x=15
(x<10)&&(x<2)

[1] FALSE

In [90]:
x=c(8,18)