In [1]:
c(2,3,5,7) + c(-2,-3, -5, 8)

[1]  0  0  0 15

In [2]:
2^3

[1] 8

In [3]:
2**3

[1] 8

In [4]:
2^0.5

[1] 1.414214

In [5]:
2**0.5

[1] 1.414214

In [6]:
2^-0.5

[1] 0.7071068

In [7]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [8]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

In [9]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [10]:
2%/%2

[1] 1

In [11]:
5%/%2

[1] 2

In [12]:
7%/%3

[1] 2

In [13]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [14]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [15]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [16]:
2 %% 2

[1] 0

In [17]:
3 %% 2

[1] 1

In [18]:
7 %% 3

[1] 1

In [19]:
7 %% 4

[1] 3

In [20]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [21]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [22]:
max(1.2, 3.4, -7.8)

[1] 3.4

In [23]:
max( c(1.2, 3.4, -7.8) )

[1] 3.4

In [24]:
min(1.2, 3.4, -7.8)

[1] -7.8

In [25]:
min( c(1.2, 3.4, -7.8) )

[1] -7.8

In [26]:
mean(2, 3, 4)

[1] 2

In [27]:
mean(c(2,3,4))

[1] 3

In [28]:
abs(-4)

[1] 4

In [29]:
abs(c(-1,-2,-3,4,5))

[1] 1 2 3 4 5

In [30]:
sqrt(4)

[1] 2

In [31]:
sqrt(c(4,9,16,25))

[1] 2 3 4 5

In [32]:
 sum(c(2,3,5,7))

[1] 17

In [33]:
 prod(c(2,3,5,7))

[1] 210

In [34]:
round(1.23)

[1] 1

In [35]:
round(1.83)

[1] 2

In [36]:
log(10)

[1] 2.302585

In [37]:
log(exp(1))

[1] 1

In [38]:
log(c(10, 100, 1000))

[1] 2.302585 4.605170 6.907755

In [39]:
log10(10)

[1] 1

In [40]:
log10(100)

[1] 2

In [41]:
log10(c(10, 100, 1000))

[1] 1 2 3

In [43]:
x1 = c(1,2,3,4)
x1

[1] 1 2 3 4

In [44]:
x2 = x1^2
x2

[1]  1  4  9 16

In [46]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

In [47]:
abs( c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)) )

[1] 19 18 17 16

In [48]:
 x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8) )

In [50]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [51]:
x[3,2]

[1] 7

In [52]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8))

In [53]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [54]:
y = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8), byrow = TRUE)

In [55]:
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [56]:
x = matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8) )

In [57]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [58]:
 dim(x)

[1] 4 2

In [59]:
nrow(x)

[1] 4

In [60]:
ncol(x)

[1] 2

In [61]:
mode(x)

[1] "numeric"

In [62]:
attributes(x)

$dim
[1] 4 2

In [63]:
help("matrix")

In [64]:
data.matrix

function (frame, rownames.force = NA)
{
    if (!is.data.frame(frame))
        return(as.matrix(frame))
    d <- dim(frame)
    rn <- if (isFALSE(rownames.force))
        NULL
    else if (isTRUE(rownames.force))
        row.names(frame)
    else if (.row_names_info(frame) <= 0L)
        NULL
    else row.names(frame)
    for (i in seq_len(d[2L])) {
        xi <- frame[[i]]
        if (is.integer(xi) || is.numeric(xi))
            next
        if (is.logical(xi) || is.factor(xi)) {
            frame[[i]] <- as.integer(xi)
            next
        }
        if (is.character(xi)) {
            frame[[i]] <- as.integer(factor(xi))
            next
        }
        frame[[i]] <- if (isS4(xi))
            methods::as(xi, "numeric")
        else as.numeric(xi)
    }
    intOK <- all(unlist(lapply(frame, is.integer)))
    x <- matrix(if (intOK)
        NA_integer_
    else NA_real_, nrow = d[1L], ncol = d[2L], dimnames = list(rn,
        names(frame)))
    for (i in seq_len(d[2L])) x[, i] <- frame[[i]]
    x
}
<bytecode: 0x56d22f28ed10>
<environment: namespace:base>